spring:
  # Spring JMS Settings
  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true
      concurrency: 2
      max-concurrency: 2
    pub-sub-domain: true
    template:
      default-destination:
      delivery-mode: non_persistent
      priority: 9
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000
  # Embedded ActiveMQ Configuration Example
  activemq:
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
    in-memory: true
    non-blocking-redelivery: true
    packages:
      trust-all: false
      trusted: com.example.spring.messaging
    pool:
      block-if-full: true
      block-if-full-timeout: -1
      enabled: false
      idle-timeout: 30000
      max-connections: 1
      time-between-expiration-check: -1
      use-anonymous-producers: true

#logging:
#  pattern:
#    console: "%date{ISO8601} [%thread]:%msg%n"
#  level:
#    root: INFO
#    org.springframework: INFO
#    com.example.spring.messaging: DEBUG